-- Legacy 104-match tournament data has been archived to seed.legacy.sql
-- The active competition does not depend on the old identifiers (e.g. R32_073, F_104).
-- This file is intentionally left blank. 
